AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Launch an EC2 instance with a public IP using user-selected VPC, Subnet, Key Pair, 
  Security Group, EBS volume size, and custom instance Name.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select the existing VPC.

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Select the existing public subnet.

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Choose an existing EC2 Key Pair for SSH access.

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Choose an existing security group to associate with the EC2 instance.

  InstanceName:
    Type: String
    Description: Name tag to assign to the EC2 instance.
    Default: MyEC2Instance

  EbsVolumeSize:
    Type: Number
    Description: Size (in GB) of the EBS root volume.
    Default: 8
    MinValue: 8
    MaxValue: 1024

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 AMI (Change as per region)
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !Ref EbsVolumeSize
            VolumeType: gp2
            DeleteOnTermination: true
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetId
          AssociatePublicIpAddress: true
          GroupSet:
            - !Ref SecurityGroupId
      Tags:
        - Key: Name
          Value: !Ref InstanceName

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance

  PublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
