AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an S3 bucket using a parameter
Parameters: 
  BucketNameParam:
    Type: String
    Description: Enter your bucket Name

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketNameParam

Outputs:
  BucketName:
    Description: Name of the created bucket
    Value: !Ref BucketNameParam